### ISSUE TITLE
numpy.distutils deprecated

### ISSUE THREAD

**Issue by tharbach** [carichte/rexs#1]
The `distutils` module of numpy is deprecated and has been removed in python 3.12. See https://numpy.org/doc/stable/reference/distutils.html for further details.

Therefore this packages is currently unusable for python 3.12 or newer. 

~~~
$ git clone https://github.com/carichte/rexs.git
$ python -m pip install .
Processing /home/manager/test/rexs
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/manager/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", >
          main()
        File "/home/manager/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", n
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/manager/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", l
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-12x0re4j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in l
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-12x0re4j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in s
          self.run_setup()
        File "/tmp/pip-build-env-12x0re4j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 516, in p
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-12x0re4j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in p
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
$ python -V
Python 3.12.4
$ pip list
Package Version
------- -------
numpy   2.1.2
pip     24.2
~~~

**Comment by usebailei** [comment]
​​Thank you so much for letting me know. No wonder I got the rexs error when trying to run import rexs in Python 3.12.8, as shown below:​
import rexs
  File "D:\Python3.12.8\Lib\site-packages\rexs\__init__.py", line 8, in <module>
    from . import xray
  File "D:\Python3.12.8\Lib\site-packages\rexs\xray\__init__.py", line 12, in <module>
    from . import absorption
  File "D:\Python3.12.8\Lib\site-packages\rexs\xray\absorption.py", line 13, in <module>
    from . import interactions as xi
  File "D:\Python3.12.8\Lib\site-packages\rexs\xray\interactions.py", line 27, in <module>
    from . import deltaf
  File "D:\Python3.12.8\Lib\site-packages\rexs\xray\deltaf\__init__.py", line 4, in <module>
    from . import deltaf
ImportError: DLL load failed while importing deltaf: The specified module could not be found.

**Comment by carichte** [comment]
This is solved with the current version of the package: 

```
[richter@num-topas ~]$ python -m pip install git+https://github.com/carichte/rexs.git
Collecting git+https://github.com/carichte/rexs.git
  Cloning https://github.com/carichte/rexs.git to /tmp/pip-req-build-di2en_a9
  Running command git clone --quiet https://github.com/carichte/rexs.git /tmp/pip-req-build-di2en_a9
  Resolved https://github.com/carichte/rexs.git to commit 0dc95102940197e4feed8393cd9b68e70fc9727b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/groups/synchrotron/miniconda3.12/lib/python3.12/site-packages (from rexs==0.2) (2.1.3)
Requirement already satisfied: scipy in /home/groups/synchrotron/miniconda3.12/lib/python3.12/site-packages (from rexs==0.2) (1.14.1)
Requirement already satisfied: meson in /home/groups/synchrotron/miniconda3.12/lib/python3.12/site-packages (from rexs==0.2) (1.6.1)
Requirement already satisfied: ninja in /home/groups/synchrotron/miniconda3.12/lib/python3.12/site-packages (from rexs==0.2) (1.11.1.3)
Requirement already satisfied: six in /home/groups/synchrotron/miniconda3.12/lib/python3.12/site-packages (from rexs==0.2) (1.17.0)
[richter@num-topas ~]$ python
Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rexs
>>> 
```
